/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Filipe
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
                 
        this.setLocationRelativeTo(null);
        
       
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_cadastrar_professor = new javax.swing.JLabel();
        edt_nome = new javax.swing.JTextField();
        lbl_nome = new javax.swing.JLabel();
        lbl_matricula = new javax.swing.JLabel();
        edt_matricula = new javax.swing.JTextField();
        lbl_turno = new javax.swing.JLabel();
        cb_matutino = new javax.swing.JCheckBox();
        cb_vespertino = new javax.swing.JCheckBox();
        cb_noturno = new javax.swing.JCheckBox();
        lbl_preferencias = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        edt_preferencias = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        lbl_exemplo = new javax.swing.JLabel();
        lbl_campos_obrigatorios = new javax.swing.JLabel();
        lbl_dica = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_cadastrar_professor.setText("Cadastrar Professor");

        edt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_nomeActionPerformed(evt);
            }
        });

        lbl_nome.setText(" Nome *");

        lbl_matricula.setText("Matrícula *");

        lbl_turno.setText("Turno *");

        cb_matutino.setText("Matutino");
        cb_matutino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_matutinoActionPerformed(evt);
            }
        });

        cb_vespertino.setText("Vespertino");
        cb_vespertino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_vespertinoActionPerformed(evt);
            }
        });

        cb_noturno.setText("Noturno");
        cb_noturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_noturnoActionPerformed(evt);
            }
        });

        lbl_preferencias.setText("Preferência de Disciplinas:");

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        lbl_exemplo.setText("Digite as disciplinas separadas por virgula. Ex: COMP089, COMP332");

        lbl_campos_obrigatorios.setText("* Campos obrigatórios");

        lbl_dica.setText("O professor pode escolher 0 (zero) ou mais disciplinas preferenciais. ");

        jLabel3.setText("O professor deve escolher pelo menos um dos 3 (três) turnos.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_matricula)
                            .addComponent(lbl_nome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edt_nome)
                            .addComponent(edt_matricula)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_preferencias)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(lbl_cadastrar_professor))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(btn_cancelar)
                                .addGap(69, 69, 69)
                                .addComponent(btn_cadastrar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_turno)
                                    .addGap(39, 39, 39)
                                    .addComponent(cb_matutino)
                                    .addGap(36, 36, 36)
                                    .addComponent(cb_vespertino)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_noturno))
                                .addComponent(edt_preferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_exemplo)
                            .addComponent(lbl_campos_obrigatorios)
                            .addComponent(lbl_dica)
                            .addComponent(jLabel3))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbl_cadastrar_professor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_matricula)
                    .addComponent(edt_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_matutino)
                    .addComponent(lbl_turno)
                    .addComponent(cb_vespertino)
                    .addComponent(cb_noturno))
                .addGap(9, 9, 9)
                .addComponent(lbl_preferencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edt_preferencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_exemplo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_campos_obrigatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_dica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_cadastrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_nomeActionPerformed

    private void cb_matutinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_matutinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_matutinoActionPerformed

    private void cb_vespertinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_vespertinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_vespertinoActionPerformed

    private void cb_noturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_noturnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_noturnoActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Inicio().setVisible(true);
        
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        String disciplinas;
        disciplinas = edt_preferencias.getText();
        String nome = edt_nome.getText();
        String matricula = edt_matricula.getText();
        String matutino = Boolean.toString(cb_matutino.isSelected());
        String vespertino = Boolean.toString(cb_vespertino.isSelected());
        String noturno = Boolean.toString(cb_noturno.isSelected());
        if(nome.trim().length()<1){
            JOptionPane.showMessageDialog(this.rootPane, "Nome não pode ser vazio!");           
        }else{
            if(matricula.trim().length()<1){
                JOptionPane.showMessageDialog(this.rootPane, "Matrícula não pode ser vazia!"); 
            }else{
                if(!cb_matutino.isSelected() && !cb_vespertino.isSelected() && !cb_noturno.isSelected()){
                    JOptionPane.showMessageDialog(this.rootPane, "Escolha algum dos 3 (três) turnos!");
                    
                }else{
                    BufferedWriter buffWrite;
                    try {
                        buffWrite = new BufferedWriter(new FileWriter("professor.txt", true));
                        buffWrite.append(matricula+","+nome+","+matutino+","+vespertino+","+noturno+","+disciplinas);
                        buffWrite.newLine();
                        buffWrite.close();
                    } catch (IOException ex) {
                        Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(this.rootPane, "Professor Cadastrado com sucesso!");
                    dispose();
                    new Inicio().setVisible(true);
                }
            }
        }       
        
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JCheckBox cb_matutino;
    private javax.swing.JCheckBox cb_noturno;
    private javax.swing.JCheckBox cb_vespertino;
    private javax.swing.JTextField edt_matricula;
    private javax.swing.JTextField edt_nome;
    private javax.swing.JTextField edt_preferencias;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_cadastrar_professor;
    private javax.swing.JLabel lbl_campos_obrigatorios;
    private javax.swing.JLabel lbl_dica;
    private javax.swing.JLabel lbl_exemplo;
    private javax.swing.JLabel lbl_matricula;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_preferencias;
    private javax.swing.JLabel lbl_turno;
    // End of variables declaration//GEN-END:variables
}
